# Generated by Django 2.1.2 on 2018-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_flavors_type_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavors',
            name='ram',
            field=models.CharField(max_length=255),
        ),
    ]
