# Generated by Django 2.1.2 on 2018-11-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_auto_20181129_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavors',
            name='type_disk',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
