# Generated by Django 2.1.3 on 2018-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='created',
        ),
        migrations.AddField(
            model_name='images',
            name='i_d',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='i_d',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
