# Generated by Django 2.1.3 on 2018-12-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_server_i_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
    ]
