version: '3'

services:
  nginx: 
    build: ./nginx
    depends_on:
      - web
    volumes:
      - type: volume
          - source: default
          target: /etc/nginx/conf.d/default.conf
          volume:
            nocopy: true
      - type: bind
          source: ./static
          target: /static
    ports:
      - "443:443"
      - "80:80"
  db:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    volumes:
      - ./dockermysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: kvm_vdi
      MYSQL_ROOT_PASSWORD: 123456
  rd:
    image: redis:2.8
    restart: always
    expose:
      - "6379"
    volumes:
      - ./dockerredis:/var/lib/redis
  web:
    build: .
    volumes:
      - ./kvmvdi:/home/kvmvdi
      - ./static:/static
    expose:
      - "8889"
      - "8443"
    depends_on:
      - rd
      - db
