# Generated by Django 2.1.2 on 2018-11-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_flavors_i_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavors',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flavors',
            name='type_disk',
        ),
    ]
