# Generated by Django 2.1.2 on 2018-11-29 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_sshkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subnets_associated', models.CharField(max_length=255)),
                ('shared', models.IntegerField()),
                ('external', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('admin_state_up', models.IntegerField()),
            ],
            options={
                'db_table': 'client_networks',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='flavors',
            old_name='thong_so',
            new_name='price',
        ),
        migrations.AddField(
            model_name='flavors',
            name='disk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavors',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavors',
            name='vcpus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sshkeys',
            name='owner',
            field=models.ForeignKey(db_column='owner', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oders',
            name='server',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='networks',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
